# Generated by Django 5.1.3 on 2025-06-05 07:38

import store.models
import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_productimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=thumbnails.fields.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=thumbnails.fields.ImageField(null=True, upload_to=store.models.path_and_rename),
        ),
    ]
