# Generated by Django 5.2.2 on 2025-06-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productattribute_alter_category_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(related_name='attributes', to='store.productattributevalue'),
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variants/')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
