# Generated by Django 5.2.2 on 2025-06-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_productvariant_attributes_productvariantimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
