# Generated by Django 5.2.2 on 2025-06-08 20:42

import store.models
import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to=store.models.path_and_rename),
        ),
    ]
